all:
  hosts:
    bastion:
      ansible_connection: local
    allinone01:
      ansible_host: 192.168.211.76
    allinone02:
      ansible_host: 192.168.211.37
    zk03:
      ansible_host: 192.168.211.107
  vars:
    zuul_tenant_name: openlaballinone
    zookeeper_ha_mode: true
  children:
    nodepool:
      children:
        nodepool-builder:
          hosts:
            allinone01:
            allinone02:
        nodepool-launcher:
          hosts:
            allinone01:
            allinone02:
      vars:
        nodepool_file_nodepool_yaml_src: "{{ labkeeper_src_dir }}/tests/nodepool/fake-nodepool.yaml.j2"
        nodepool_clouds_src: "{{ labkeeper_config_git_dest }}/nodepool/fake-clouds.yaml.j2"
    zuul:
      children:
        zuul-scheduler:
          hosts:
            allinone01:
            allinone02:
        zuul-executor:
          hosts:
            allinone01:
            allinone02:
        zuul-web:
          hosts:
            allinone01:
            allinone02:
        zuul-merger:
          hosts:
            allinone01:
            allinone02:
        zuul-fingergw:
          hosts:
            allinone01:
            allinone02:
        zuul-log-server:
          hosts:
            allinone01:
            allinone02:
      vars:
        github_app_id: 0000
        github_webhook_token: "test"
        zuul_tenant_name: test
        zuul_public_ip: ""
    gear:
      hosts:
        allinone01:
        allinone02:
    statsd:
      hosts:
        allinone01:
        allinone02:
    zookeeper:
      hosts:
        allinone01:
        allinone02:
        zk03:
    mysql:
      hosts:
        allinone01:
        allinone02:
    apache:
      hosts:
        allinone01:
        allinone02:

    openlab-master:
      hosts: allinone01
      vars:
        zk_myid: 1
    openlab-slave:
      hosts: allinone02
      vars:
        zk_myid: 2
    openlab-zk3:
      hosts: zk03
      vars:
        zk_myid: 3
