all:
  hosts:
    bastion:
      ansible_connection: local
    aio_test01:
      ansible_host: 127.0.0.1
    aio_test02:
      ansible_host: 192.168.211.174
    #test_zk03:
    #  ansible_host: 192.168.211.151
  vars:
    zuul_tenant_name: aio_test_ha
    zookeeper_ha_mode: true
  children:
    nodepool:
      children:
        nodepool-builder:
          hosts:
            aio_test01:
            aio_test02:
          vars:
            nodepool_builder_id: "8fcf0492-b972-45cc-828f-efd6b301b46e"
        nodepool-launcher:
          hosts:
            aio_test01:
            aio_test02:
      vars:
        nodepool_file_nodepool_yaml_src: "{{ labkeeper_config_git_dest }}/nodepool/allinone-nodepool.yaml.j2"
        nodepool_clouds_src: "{{ labkeeper_config_git_dest }}/nodepool/openlab-clouds.yaml.j2"
    zuul:
      children:
        zuul-scheduler:
          hosts:
            aio_test01:
            aio_test02:
        zuul-executor:
          hosts:
            aio_test01:
            aio_test02:
        zuul-web:
          hosts:
            aio_test01:
            aio_test02:
        zuul-merger:
          hosts:
            aio_test01:
            aio_test02:
        zuul-fingergw:
          hosts:
            aio_test01:
            aio_test02:
        zuul-log-server:
          children:
            logserver-master:
              hosts: aio_test01
            logserver-slave:
              hosts: aio_test02
        zuul-master:
          hosts: aio_test01
          vars:
            zuul_public_ip: 80.158.7.1
        zuul-slave:
          hosts: aio_test02
          vars:
            zuul_public_ip: 80.158.7.2
      vars:
        github_app_id: 0000
        github_webhook_token: "aio_test_ha"
        zuul_tenant_name: aio_test_ha
        zuul_public_ip: ""
    gear:
      hosts:
        aio_test01:
        aio_test02:
    statsd:
      hosts:
        aio_test01:
        aio_test02:
    zookeeper:
      children:
        zk-master:
          hosts: aio_test01
          vars:
            zk_myid: 1
        zk-slave:
          hosts: aio_test02
          vars:
            zk_myid: 2
        #zk-03:
        #  hosts: zk03
        #  vars:
        #    zk_myid: 3
    mysql:
      children:
        mysql-master:
          hosts: aio_test01
          vars:
            mysql_server_id: 1
        mysql-slave:
          hosts: aio_test02
          vars:
            mysql_server_id: 2
    apache:
      hosts:
        aio_test01:
        aio_test02:
